# Text Representation

1. What is Feature Extraction from text?
2. Why do we need it?
3. Why is it difficult?
4. What is the core idea?
5. What are the techniques?


NLP PipeLine
1. Acquisition
2. Text Preprocessing
3. Text Vectorization
4. Algorithms


Corpus,Vocabulary,Document,Word


1.One hot Encoding
2.Bag of words(Text Classification)


In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame({'text': [
        'people watch campusx','campusx watch campusx','people write comment','campusx write comment' ], 'output': [1, 1, 0, 0]})
print(df)

                    text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0


In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,3))

In [5]:
bow = cv.fit_transform(df['text'])

In [6]:
#vocab 
print(cv.vocabulary_)

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}


In [7]:
print(len(cv.vocabulary_))

15


In [8]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 0 0 0 0 1 1 1 0 0 1 1 0 0]]
[[2 1 1 0 0 0 0 0 0 0 0 1 1 0 0]]


In [9]:
cv.transform(["campusx watch and write comment df campusx"]).toarray()

array([[2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1]])

In [10]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [12]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]
['campusx' 'comment' 'people' 'watch' 'write']
